/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.rawmaterials;

/**
 *
 * @author memam
 */
public class WarehouseView extends javax.swing.JFrame {

    /**
     * Creates new form Warehouse
     */
    public WarehouseView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCompanyHeader = new javax.swing.JPanel();
        jpLoginInfo = new javax.swing.JPanel();
        jlblLoginName = new javax.swing.JLabel();
        jtfLoginName = new javax.swing.JTextField();
        jlblLoginDate = new javax.swing.JLabel();
        jftLoginDate = new javax.swing.JFormattedTextField();
        jlblLoginTime = new javax.swing.JLabel();
        jftLoginTime = new javax.swing.JFormattedTextField();
        jspInventory = new javax.swing.JScrollPane();
        jtInventory = new javax.swing.JTable();
        jbtnAddNewMaterial = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jlblCodeFilteration = new javax.swing.JLabel();
        jcbCodeFilteration = new javax.swing.JComboBox();
        jlblTypeFilteration = new javax.swing.JLabel();
        jcbTypeFilteration1 = new javax.swing.JComboBox();
        jpAddQty = new javax.swing.JPanel();
        jlblAddQtyCode = new javax.swing.JLabel();
        jcbAddQtyCode = new javax.swing.JComboBox();
        jlblAddQtyQty = new javax.swing.JLabel();
        jftAddQtyQty = new javax.swing.JFormattedTextField();
        jbtnAddQty = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlblWithdrawQtyCode = new javax.swing.JLabel();
        jftWithdrawQtyQty = new javax.swing.JFormattedTextField();
        jcbWithdrawQtyCode = new javax.swing.JComboBox();
        jlblWithdrawQtyQty = new javax.swing.JLabel();
        jlblWithdrawEmployee = new javax.swing.JLabel();
        jcbWithdrawEmployee = new javax.swing.JComboBox();
        jbtnWithdrawQty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCompanyHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "أسم الشركة", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jpLoginInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بيانات الدخول", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jlblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblLoginName.setText("الأسم");

        jtfLoginName.setEditable(false);

        jlblLoginDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblLoginDate.setText("تاريخ الدخول");

        jftLoginDate.setEditable(false);
        jftLoginDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jlblLoginTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblLoginTime.setText("وقت الدخول");

        jftLoginTime.setEditable(false);
        jftLoginTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jpLoginInfoLayout = new javax.swing.GroupLayout(jpLoginInfo);
        jpLoginInfo.setLayout(jpLoginInfoLayout);
        jpLoginInfoLayout.setHorizontalGroup(
            jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginInfoLayout.createSequentialGroup()
                        .addComponent(jftLoginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jlblLoginDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlblLoginName))
                    .addGroup(jpLoginInfoLayout.createSequentialGroup()
                        .addComponent(jftLoginTime, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jlblLoginTime)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpLoginInfoLayout.setVerticalGroup(
            jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLoginName)
                    .addComponent(jtfLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblLoginDate)
                    .addComponent(jftLoginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLoginTime)
                    .addComponent(jftLoginTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jspInventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "جرد", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jtInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "الكمية", "الصنف", "الأسم", "كود"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtInventory.setColumnSelectionAllowed(true);
        jtInventory.getTableHeader().setReorderingAllowed(false);
        jspInventory.setViewportView(jtInventory);
        jtInventory.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jbtnAddNewMaterial.setText("أضف خامة جديدة");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlblCodeFilteration.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblCodeFilteration.setText("جرد لكود");

        jcbCodeFilteration.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblTypeFilteration.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblTypeFilteration.setText("جرد لنوع");

        jcbTypeFilteration1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jpAddQty.setBorder(javax.swing.BorderFactory.createTitledBorder("إضافة كمية"));

        jlblAddQtyCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblAddQtyCode.setText("كود");

        jcbAddQtyCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblAddQtyQty.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblAddQtyQty.setText("كمية");

        jftAddQtyQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jbtnAddQty.setText("إضافة");

        javax.swing.GroupLayout jpAddQtyLayout = new javax.swing.GroupLayout(jpAddQty);
        jpAddQty.setLayout(jpAddQtyLayout);
        jpAddQtyLayout.setHorizontalGroup(
            jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddQtyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnAddQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpAddQtyLayout.createSequentialGroup()
                        .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftAddQtyQty)
                            .addComponent(jcbAddQtyCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblAddQtyCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblAddQtyQty, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jpAddQtyLayout.setVerticalGroup(
            jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddQtyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAddQtyCode)
                    .addComponent(jcbAddQtyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAddQtyQty)
                    .addComponent(jftAddQtyQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAddQty)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("صرف خامة"));

        jlblWithdrawQtyCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblWithdrawQtyCode.setText("كــــود");

        jftWithdrawQtyQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jcbWithdrawQtyCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlblWithdrawQtyQty.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblWithdrawQtyQty.setText("كـــمية");

        jlblWithdrawEmployee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblWithdrawEmployee.setText("موظف");

        jcbWithdrawEmployee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnWithdrawQty.setText("صرف");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbtnWithdrawQty, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jftWithdrawQtyQty)
                            .addComponent(jcbWithdrawQtyCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblWithdrawQtyCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblWithdrawQtyQty, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbWithdrawEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblWithdrawEmployee)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblWithdrawQtyCode)
                    .addComponent(jcbWithdrawQtyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblWithdrawQtyQty)
                    .addComponent(jftWithdrawQtyQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnWithdrawQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblWithdrawEmployee)
                    .addComponent(jcbWithdrawEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCompanyHeaderLayout = new javax.swing.GroupLayout(jpCompanyHeader);
        jpCompanyHeader.setLayout(jpCompanyHeaderLayout);
        jpCompanyHeaderLayout.setHorizontalGroup(
            jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpAddQty, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addComponent(jbtnAddNewMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbTypeFilteration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlblTypeFilteration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbCodeFilteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlblCodeFilteration)
                        .addContainerGap())
                    .addComponent(jspInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)))
        );
        jpCompanyHeaderLayout.setVerticalGroup(
            jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                .addComponent(jpLoginInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addComponent(jspInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnAddNewMaterial)
                            .addComponent(jlblCodeFilteration)
                            .addComponent(jcbCodeFilteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTypeFilteration)
                            .addComponent(jcbTypeFilteration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpAddQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 158, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCompanyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCompanyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WarehouseView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAddNewMaterial;
    private javax.swing.JButton jbtnAddQty;
    private javax.swing.JButton jbtnWithdrawQty;
    private javax.swing.JComboBox jcbAddQtyCode;
    private javax.swing.JComboBox jcbCodeFilteration;
    private javax.swing.JComboBox jcbTypeFilteration1;
    private javax.swing.JComboBox jcbWithdrawEmployee;
    private javax.swing.JComboBox jcbWithdrawQtyCode;
    private javax.swing.JFormattedTextField jftAddQtyQty;
    private javax.swing.JFormattedTextField jftLoginDate;
    private javax.swing.JFormattedTextField jftLoginTime;
    private javax.swing.JFormattedTextField jftWithdrawQtyQty;
    private javax.swing.JLabel jlblAddQtyCode;
    private javax.swing.JLabel jlblAddQtyQty;
    private javax.swing.JLabel jlblCodeFilteration;
    private javax.swing.JLabel jlblLoginDate;
    private javax.swing.JLabel jlblLoginName;
    private javax.swing.JLabel jlblLoginTime;
    private javax.swing.JLabel jlblTypeFilteration;
    private javax.swing.JLabel jlblWithdrawEmployee;
    private javax.swing.JLabel jlblWithdrawQtyCode;
    private javax.swing.JLabel jlblWithdrawQtyQty;
    private javax.swing.JPanel jpAddQty;
    private javax.swing.JPanel jpCompanyHeader;
    private javax.swing.JPanel jpLoginInfo;
    private javax.swing.JScrollPane jspInventory;
    private javax.swing.JTable jtInventory;
    private javax.swing.JTextField jtfLoginName;
    // End of variables declaration//GEN-END:variables
}
