/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.RawMaterial;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author memam
 */
public class WarehouseView extends javax.swing.JFrame {

    /**
     * Creates new form Warehouse
     */
    public WarehouseView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCompanyHeader = new javax.swing.JPanel();
        jpLoginInfo = new javax.swing.JPanel();
        jlblLoginName = new javax.swing.JLabel();
        jtfLoginName = new javax.swing.JTextField();
        jlblLoginDate = new javax.swing.JLabel();
        jftLoginDate = new javax.swing.JFormattedTextField();
        jlblLoginTime = new javax.swing.JLabel();
        jftLoginTime = new javax.swing.JFormattedTextField();
        jspInventory = new javax.swing.JScrollPane();
        jtInventory = new javax.swing.JTable();
        jSeparator = new javax.swing.JSeparator();
        jlblCodeFilteration = new javax.swing.JLabel();
        jcbCodeFilteration = new javax.swing.JComboBox();
        jlblTypeFilteration = new javax.swing.JLabel();
        jcbTypeFilteration = new javax.swing.JComboBox();
        jpAddQty = new javax.swing.JPanel();
        jlblAddQtyCode = new javax.swing.JLabel();
        jcbAddQtyCode = new javax.swing.JComboBox();
        jlblAddQtyQty = new javax.swing.JLabel();
        jftAddQtyQty = new javax.swing.JFormattedTextField();
        jbtnAddQty = new javax.swing.JButton();
        jpWithdrawQty = new javax.swing.JPanel();
        jlblWithdrawQtyCode = new javax.swing.JLabel();
        jftWithdrawQtyQty = new javax.swing.JFormattedTextField();
        jcbWithdrawQtyCode = new javax.swing.JComboBox();
        jlblWithdrawQtyQty = new javax.swing.JLabel();
        jlblWithdrawEmployee = new javax.swing.JLabel();
        jcbWithdrawEmployee = new javax.swing.JComboBox();
        jbtnWithdrawQty = new javax.swing.JButton();
        jpAddMaterial = new javax.swing.JPanel();
        jbtnAddNewMaterial = new javax.swing.JButton();
        jlblMaterialName = new javax.swing.JLabel();
        jtfMaterialName = new javax.swing.JTextField();
        jlblMaterialDesc = new javax.swing.JLabel();
        jtfMaterialDesc = new javax.swing.JTextField();
        jlblMaterialQty = new javax.swing.JLabel();
        jftMaterialQty = new javax.swing.JFormattedTextField();
        jlblMaterialPrice = new javax.swing.JLabel();
        jftMaterialPrice = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCompanyHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "أسم الشركة", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jpLoginInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بيانات الدخول", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jlblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblLoginName.setText("الأسم");

        jtfLoginName.setEditable(false);

        jlblLoginDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblLoginDate.setText("تاريخ الدخول");

        jftLoginDate.setEditable(false);
        jftLoginDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jlblLoginTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblLoginTime.setText("وقت الدخول");

        jftLoginTime.setEditable(false);
        jftLoginTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jpLoginInfoLayout = new javax.swing.GroupLayout(jpLoginInfo);
        jpLoginInfo.setLayout(jpLoginInfoLayout);
        jpLoginInfoLayout.setHorizontalGroup(
            jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginInfoLayout.createSequentialGroup()
                        .addComponent(jftLoginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jlblLoginDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlblLoginName))
                    .addGroup(jpLoginInfoLayout.createSequentialGroup()
                        .addComponent(jftLoginTime, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jlblLoginTime)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpLoginInfoLayout.setVerticalGroup(
            jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLoginName)
                    .addComponent(jtfLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblLoginDate)
                    .addComponent(jftLoginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLoginTime)
                    .addComponent(jftLoginTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jspInventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "المواد الخام", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jtInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الكمية", "الوصف", "الأسم", "كود"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtInventory.setColumnSelectionAllowed(true);
        jtInventory.getTableHeader().setReorderingAllowed(false);
        jspInventory.setViewportView(jtInventory);
        jtInventory.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlblCodeFilteration.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblCodeFilteration.setText("جرد لكود");

        jlblTypeFilteration.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblTypeFilteration.setText("جرد لنوع");

        jpAddQty.setBorder(javax.swing.BorderFactory.createTitledBorder("إضافة كمية"));

        jlblAddQtyCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblAddQtyCode.setText("كود");

        jlblAddQtyQty.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblAddQtyQty.setText("كمية");

        jftAddQtyQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftAddQtyQty.setText("0");

        jbtnAddQty.setText("إضافة");

        javax.swing.GroupLayout jpAddQtyLayout = new javax.swing.GroupLayout(jpAddQty);
        jpAddQty.setLayout(jpAddQtyLayout);
        jpAddQtyLayout.setHorizontalGroup(
            jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddQtyLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnAddQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpAddQtyLayout.createSequentialGroup()
                        .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftAddQtyQty)
                            .addComponent(jcbAddQtyCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblAddQtyCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblAddQtyQty, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jpAddQtyLayout.setVerticalGroup(
            jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddQtyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAddQtyCode)
                    .addComponent(jcbAddQtyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAddQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAddQtyQty)
                    .addComponent(jftAddQtyQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAddQty)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jpWithdrawQty.setBorder(javax.swing.BorderFactory.createTitledBorder("صرف خامة"));

        jlblWithdrawQtyCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblWithdrawQtyCode.setText("كــــود");

        jftWithdrawQtyQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftWithdrawQtyQty.setText("0");

        jlblWithdrawQtyQty.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblWithdrawQtyQty.setText("كـــمية");

        jlblWithdrawEmployee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblWithdrawEmployee.setText("موظف");

        jcbWithdrawEmployee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnWithdrawQty.setText("صرف");

        javax.swing.GroupLayout jpWithdrawQtyLayout = new javax.swing.GroupLayout(jpWithdrawQty);
        jpWithdrawQty.setLayout(jpWithdrawQtyLayout);
        jpWithdrawQtyLayout.setHorizontalGroup(
            jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWithdrawQtyLayout.createSequentialGroup()
                .addComponent(jbtnWithdrawQty, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWithdrawQtyLayout.createSequentialGroup()
                        .addGroup(jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jftWithdrawQtyQty)
                            .addComponent(jcbWithdrawQtyCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblWithdrawQtyCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblWithdrawQtyQty, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWithdrawQtyLayout.createSequentialGroup()
                        .addComponent(jcbWithdrawEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblWithdrawEmployee)))
                .addContainerGap())
        );
        jpWithdrawQtyLayout.setVerticalGroup(
            jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWithdrawQtyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblWithdrawQtyCode)
                    .addComponent(jcbWithdrawQtyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblWithdrawQtyQty)
                    .addComponent(jftWithdrawQtyQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnWithdrawQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpWithdrawQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblWithdrawEmployee)
                    .addComponent(jcbWithdrawEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpAddMaterial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "أضف خامة", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jbtnAddNewMaterial.setText("أضف");

        jlblMaterialName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlblMaterialName.setText("أسم الخامة");

        jlblMaterialDesc.setText("وصف الخامة");

        jlblMaterialQty.setText("الكمية");

        jftMaterialQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftMaterialQty.setText("0");

        jlblMaterialPrice.setText("السعر");

        jftMaterialPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jftMaterialPrice.setText("0");

        javax.swing.GroupLayout jpAddMaterialLayout = new javax.swing.GroupLayout(jpAddMaterial);
        jpAddMaterial.setLayout(jpAddMaterialLayout);
        jpAddMaterialLayout.setHorizontalGroup(
            jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddMaterialLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddMaterialLayout.createSequentialGroup()
                        .addComponent(jftMaterialQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblMaterialQty))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddMaterialLayout.createSequentialGroup()
                        .addComponent(jftMaterialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblMaterialPrice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnAddNewMaterial)
                    .addGroup(jpAddMaterialLayout.createSequentialGroup()
                        .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMaterialDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblMaterialDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblMaterialName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpAddMaterialLayout.setVerticalGroup(
            jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddMaterialLayout.createSequentialGroup()
                        .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblMaterialName)
                            .addComponent(jtfMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMaterialDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblMaterialDesc)))
                    .addGroup(jpAddMaterialLayout.createSequentialGroup()
                        .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblMaterialQty)
                            .addComponent(jftMaterialQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblMaterialPrice)
                            .addComponent(jftMaterialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAddNewMaterial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCompanyHeaderLayout = new javax.swing.GroupLayout(jpCompanyHeader);
        jpCompanyHeader.setLayout(jpCompanyHeaderLayout);
        jpCompanyHeaderLayout.setHorizontalGroup(
            jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addComponent(jpWithdrawQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpAddQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpAddMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbTypeFilteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlblTypeFilteration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbCodeFilteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jlblCodeFilteration)
                        .addContainerGap())
                    .addComponent(jspInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)))
        );
        jpCompanyHeaderLayout.setVerticalGroup(
            jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                .addComponent(jpLoginInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addComponent(jspInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCodeFilteration)
                            .addComponent(jcbCodeFilteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTypeFilteration)
                            .addComponent(jcbTypeFilteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator)
                    .addGroup(jpCompanyHeaderLayout.createSequentialGroup()
                        .addGroup(jpCompanyHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpAddQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpWithdrawQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpAddMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCompanyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCompanyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addNewMaterialListener(ActionListener listener) {
        jbtnAddNewMaterial.addActionListener(listener);
    }

    public void addExtraQtyListener(ActionListener listener) {
        jbtnAddQty.addActionListener(listener);
    }

    public void addWithdrawSomeMaterialListener(ActionListener listener) {
        jbtnWithdrawQty.addActionListener(listener);
    }

    /**
     *
     * @param codes
     */
    public void setupMaterialsCode(Set<Integer> codes) {
        this.materialsCode = codes;
        this.materialsCode.stream().map((code) -> {
            jcbAddQtyCode.addItem(code);
            return code;
        }).forEach((code) -> {
            jcbWithdrawQtyCode.addItem(code);
        });
    }

    public void updateMaterialQty(int id, int qty) {
        jtInventory.getModel().setValueAt(qty, new ArrayList<>(this.materialsCode).indexOf(id), 0);
    }

    public void addNewMaterial(int id, String name, String desc, int qty, int price) {
        DefaultTableModel model = (DefaultTableModel) jtInventory.getModel();
        model.addRow(new Object[]{qty, desc, name, id});
    }

    /**
     *
     * @return values of material ID and material added quantity
     */
    public int[] getExtraQtyInfo() {
        int[] codeQty = new int[2];

        codeQty[0] = (Integer) jcbAddQtyCode.getSelectedItem();
        codeQty[1] = Integer.parseInt(jftAddQtyQty.getText());

        return codeQty;
    }

    /**
     *
     * @return values of material ID and material withdrawn quantity
     */
    public int[] getWithdrawQtyInfo() {
        int[] codeQty = new int[2];

        codeQty[0] = (Integer) jcbWithdrawQtyCode.getSelectedItem();

        int qty = Integer.parseInt(jftWithdrawQtyQty.getText());
        codeQty[1] = qty < 0 ? qty * -1 : qty; // if the user enters positive or negative, the result will be the same

        return codeQty;
    }

    public String getNewMaterialName() {
        return jtfMaterialName.getText();
    }

    public String getNewMaterialDesc() {
        return jtfMaterialDesc.getText();
    }

    public int getNewMaterialQty() {
        return Integer.parseInt(jftMaterialQty.getText());
    }

    public int getNewMaterialPrice() {
        return Integer.parseInt(jftMaterialPrice.getText());
    }

    public void warnUser(String message) {
        JOptionPane.showMessageDialog(this, message, "تحذير", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JButton jbtnAddNewMaterial;
    private javax.swing.JButton jbtnAddQty;
    private javax.swing.JButton jbtnWithdrawQty;
    private javax.swing.JComboBox jcbAddQtyCode;
    private javax.swing.JComboBox jcbCodeFilteration;
    private javax.swing.JComboBox jcbTypeFilteration;
    private javax.swing.JComboBox jcbWithdrawEmployee;
    private javax.swing.JComboBox jcbWithdrawQtyCode;
    private javax.swing.JFormattedTextField jftAddQtyQty;
    private javax.swing.JFormattedTextField jftLoginDate;
    private javax.swing.JFormattedTextField jftLoginTime;
    private javax.swing.JFormattedTextField jftMaterialPrice;
    private javax.swing.JFormattedTextField jftMaterialQty;
    private javax.swing.JFormattedTextField jftWithdrawQtyQty;
    private javax.swing.JLabel jlblAddQtyCode;
    private javax.swing.JLabel jlblAddQtyQty;
    private javax.swing.JLabel jlblCodeFilteration;
    private javax.swing.JLabel jlblLoginDate;
    private javax.swing.JLabel jlblLoginName;
    private javax.swing.JLabel jlblLoginTime;
    private javax.swing.JLabel jlblMaterialDesc;
    private javax.swing.JLabel jlblMaterialName;
    private javax.swing.JLabel jlblMaterialPrice;
    private javax.swing.JLabel jlblMaterialQty;
    private javax.swing.JLabel jlblTypeFilteration;
    private javax.swing.JLabel jlblWithdrawEmployee;
    private javax.swing.JLabel jlblWithdrawQtyCode;
    private javax.swing.JLabel jlblWithdrawQtyQty;
    private javax.swing.JPanel jpAddMaterial;
    private javax.swing.JPanel jpAddQty;
    private javax.swing.JPanel jpCompanyHeader;
    private javax.swing.JPanel jpLoginInfo;
    private javax.swing.JPanel jpWithdrawQty;
    private javax.swing.JScrollPane jspInventory;
    private javax.swing.JTable jtInventory;
    private javax.swing.JTextField jtfLoginName;
    private javax.swing.JTextField jtfMaterialDesc;
    private javax.swing.JTextField jtfMaterialName;
    // End of variables declaration//GEN-END:variables
    private Set<Integer> materialsCode;
}
